#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
SHORTSIG_SUCCESS = 0,
SHORTSIG_INVALID_CD = 1,
SHORTSIG_INVALID_BIT_COUNT = 2,
SHORTSIG_BAD_PUBLIC_KEY = 3,
SHORTSIG_BAD_PRIVATE_KEY = 4,
SHORTSIG_BAD_LENGTH = 5,
SHORTSIG_BIGNUM_ERROR = 6,
SHORTSIG_MAXIMUM_TRIALS = 7,
SHORTSIG_INTERNAL_ERROR = 8,
SHORTSIG_NONAUTHENTIC_CD = 9,
} WPA_SHORTSIG_STATUS;

WPA_SHORTSIG_STATUS ShortSigHash(CONST BYTE* arg_0, DWORD arg_4, CONST DWORD* arg_8, DWORD arg_C, LPDWORD arg_10, DWORD arg_14);

#ifdef __cplusplus
}
#endif
